services:
  backend:
    build:
      context: ./backend
    networks:
      - internal
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py

  frontend:
    build:
      context: ./frontend
    networks:
      - proxy
      - internal
    environment:
      - NODE_ENV=production

networks:
  proxy:
    driver: bridge
  internal:
    driver: bridge
