services:
  backend:
    build:
      context: ./backend
    ports:
      - "40348:8080"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
