services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: ${NODE_ENV:-production}
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    networks:
      - app-network
    ports:
      - "${FRONTEND_PORT:-}:8080"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - FLASK_ENV=${NODE_ENV:-production}
      - FLASK_DEBUG=${FLASK_DEBUG:-0}
    networks:
      - app-network
    ports:
      - "${BACKEND_PORT:-}:5000"

networks:
  app-network:
    driver: bridge
