services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    environment:
      - NODE_ENV=production
    networks:
      - shadowlabs_internal
      - proxy

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    networks:
      - shadowlabs_internal

networks:
  proxy:
    external: true
  shadowlabs_internal:
    driver: bridge
