services:
  backend:
    build:
      context: ./backend
    networks:
      - internal
    environment:
      - FLASK_ENV=${DEVELOPMENT:-false}
      - FLASK_APP=app.py
    ports:
      - ${DEVELOPMENT:+5000:5000} # Only expose in development mode

  frontend:
    build:
      context: ./frontend
    networks:
      - proxy
      - internal
    environment:
      - NODE_ENV=${DEVELOPMENT:-false}
    ports:
      - ${DEVELOPMENT:+3000:3000} # Only expose in development mode

networks:
  proxy:
    external: true
  internal:
    driver: bridge
