name: Build and Deploy to Production

on:
  push:
    branches: [prod]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test Docker build
        run: docker compose build

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.HETZNER_SSH_KEY }}

      - name: Copy project files to server
        run: |
          rsync -avz --exclude '.git*' --exclude 'node_modules' ./ ${{ secrets.HETZNER_USER }}@${{ secrets.HETZNER_HOST }}:/home/${{ secrets.HETZNER_USER }}/ShadowLabs

      - name: Copy .env file to server
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          scp .env ${{ secrets.HETZNER_USER }}@${{ secrets.HETZNER_HOST }}:/home/${{ secrets.HETZNER_USER }}/ShadowLabs/.env

      - name: Deploy with Docker Compose
        run: |
          ssh ${{ secrets.HETZNER_USER }}@${{ secrets.HETZNER_HOST }} "cd /home/${{ secrets.HETZNER_USER }}/ShadowLabs && docker compose up --build -d"
