name: Build and Deploy to Production

on:
  push:
    branches: [prod]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test Docker build
        run: docker compose build

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.HETZNER_SSH_KEY }}

      - name: Add server to known_hosts
        run: ssh-keyscan -H ${{ secrets.HETZNER_HOST }} >> ~/.ssh/known_hosts

      - name: Setup Git repository on server (if not exists)
        run: |
          ssh ${{ secrets.HETZNER_USER }}@${{ secrets.HETZNER_HOST }} "
            if [ ! -d '/home/${{ secrets.HETZNER_USER }}/ShadowLabs' ]; then
              mkdir -p /home/${{ secrets.HETZNER_USER }}/ShadowLabs
              cd /home/${{ secrets.HETZNER_USER }}/ShadowLabs
              git init
              git config receive.denyCurrentBranch updateInstead
            fi
          "

      - name: Push code to server using Git
        run: |
          git remote add production ${{ secrets.HETZNER_USER }}@${{ secrets.HETZNER_HOST }}:/home/${{ secrets.HETZNER_USER }}/ShadowLabs || git remote set-url production ${{ secrets.HETZNER_USER }}@${{ secrets.HETZNER_HOST }}:/home/${{ secrets.HETZNER_USER }}/ShadowLabs
          git push -f production ${{ github.ref_name }}

      - name: Deploy with Docker Compose
        run: |
          ssh ${{ secrets.HETZNER_USER }}@${{ secrets.HETZNER_HOST }} "cd /home/${{ secrets.HETZNER_USER }}/ShadowLabs && docker compose up --build -d"
